---
deployment:
  tasks:
    # GANTI 'mimz9857' dengan username cPanel Anda.
    # GANTI 'public_html' jika lokasi website Anda berbeda.
    - export DEPLOYPATH=/home/mimz9857/public_html/sikumi

    # Salin file dari repo ke folder live
    - /bin/cp -R * $DEPLOYPATH
    - /bin/cp .htaccess $DEPLOYPATH