---
deployment:
  tasks:
    - export DEPLOYPATH=/home/mimz9857/public_html/sikumi/
    - /bin/rsync -avz --exclude '.git' --exclude '.cpanel.yml' --exclude 'writable/' $cpanelroot/ $DEPLOYPATH
    - /bin/mkdir -p $DEPLOYPATH/writable/cache/
    - chmod -R 777 $DEPLOYPATH/writable/
