---
deployment:
  tasks:
    - export DEPLOYPATH=/home/mimz9857/public_html/sikumi/
    - cp -r $cpanelroot/* $DEPLOYPATH/
    - cp $cpanelroot/public/.htaccess $DEPLOYPATH/public/
    - /bin/mkdir -p $DEPLOYPATH/writable/cache/
    - /bin/mkdir -p $DEPLOYPATH/writable/logs/
    - /bin/mkdir -p $DEPLOYPATH/writable/session/
    - chmod -R 777 $DEPLOYPATH/writable/
